import Header from '@/components/Header';
import Navbar from '@/components/Navbar';
import './globals.css';
import Providers from './Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// Header와 children이 서버 사이드이지만 NextJS 13에서는
// Providers와 같은 클라이언트 사이드도 같이 랜더링 할 수 있다.

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          {/* Header */}
          <Header />

          {/* Navbar */}
          <Navbar />

          {/* SearchBox */}

          {children}
        </Providers>
      </body>
    </html>
  );
}
